import {CastAndCrew} from '/interfaces/castandcrew.ts';
export var CASTMEMBERS: CastAndCrew[] = [
{"id": 1,
"name": "Lauren McClain",
"image": "static/images/cast/lauren.jpg",
  "description": "Lauren has been a part of St. Joseph Drama Club on and off since 2007. She has her Bachelors in French from NKU and a Master in Business Informatics from NKU. She currently works at Kroger on their web team. She's married and lives with her three cats. I really just need to see this text wrap so I know that it works and I'm running out of things to type.Text Text Text Text Text Text Text Text Text",
  "isOfficer": false,
  "officePosition": ""
},
{"id": 2,
"name": "Narco",
"image": "http://placehold.it/400x300",
"description": "Description to be provided by cast member",
"isOfficer": true,
"officePosition" : "President"
},
{"id": 3,
"name": "Bombasto",
"image": "http://placehold.it/400x300",
"description": "Description to be provided by cast member",
"isOfficer": true,
"officePosition" : "Vice President"
},
{"id": 4,
"name": "Celeritas",
"image": "http://placehold.it/400x300",
"description": "Description to be provided by cast member",
"isOfficer": false,
"officePosition" : ""},
{"id": 5,
"name": "Magneta",
"image": "http://placehold.it/400x300",
"description": "Description to be provided by cast member",
"isOfficer" : false,
"officePosition" : ""},
{"id": 6,
"name": "RubberMan",
"image": "http://placehold.it/400x300",
"description": "Description to be provided by cast member",
"isOfficer" : true,
"officePosition" : "Treasurer"},
{"id": 7, "name": "Dynama", "image": "http://placehold.it/400x300", "description": "Description to be provided by cast member", "isOfficer": false, "officePosition" : ""},
{"id": 8, "name": "Dr IQ", "image": "http://placehold.it/400x300", "description": "Description to be provided by cast member", "isOfficer": false, "officePosition" : ""},
{"id": 9, "name": "Magma", "image": "http://placehold.it/400x300", "description": "Description to be provided by cast member", "isOfficer": false, "officePosition" : ""},
{"id": 10, "name": "Tornado", "image": "http://placehold.it/400x300", "description": "Description to be provided by cast member", "isOfficer": false, "officePosition" : ""}
];
